name = "knytt-frontend"
compatibility_date = "2024-01-01"

[build]
command = "cd frontend && npm ci && npm run build"
cwd = "/"
watch_dir = "frontend"

[build.upload]
dir = "frontend/.next"
format = "service-worker"

[[pages]]
project_name = "knytt-frontend"
production_branch = "main"
